<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ddalt" nsURI="http://www.example.org/ddalt" nsPrefix="ddalt">
  <eClassifiers xsi:type="ecore:EClass" name="DataDictionary">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" upperBound="-1"
        eType="#//Definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Definition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" upperBound="-1"
        eType="#//Description"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//DefinitionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="#//Description">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" lowerBound="1" eType="#//Range"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Range">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Double"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Description" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Description">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selections" upperBound="-1"
        eType="#//Selection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iterations" upperBound="-1"
        eType="#//Iteration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iteration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//DefinitionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" lowerBound="1"
        upperBound="-1" eType="#//DefinitionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Selection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" eType="#//Comment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="definitions" lowerBound="1"
        upperBound="-1" eType="#//DefinitionName"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DefinitionName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
  </eClassifiers>
</ecore:EPackage>
