<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="http://www.example.org/metamodel" nsPrefix="metamodel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&lt;p>&#xA;Inherit from this entity to make an element uniquely identifiable.&lt;br />&#xA;Identifiers&amp;nbsp;are&amp;nbsp;not&amp;nbsp;fixed&amp;nbsp;to&amp;nbsp;one&amp;nbsp;realization.&lt;br />&#xA;GUIDs&amp;nbsp;are&amp;nbsp;recommend.&amp;nbsp;GUIDs&amp;nbsp;are&amp;nbsp;described&amp;nbsp;in&amp;nbsp;their&amp;nbsp;own&amp;nbsp;model.&amp;nbsp;See&amp;nbsp;GUIDModel&amp;nbsp;(GUID.emx).&lt;br />&#xA;Identifier&amp;nbsp;implementations&amp;nbsp;can&amp;nbsp;be&amp;nbsp;found&amp;nbsp;in&amp;nbsp;external&amp;nbsp;projects&amp;nbsp;only.&#xA;&lt;/p>"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
    <details key="identifierIsUnique" value="Identifier.allInstances()->isUnique(p: Identifier | p.id)"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="constraints" value="identifierIsUnique"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowDiagram" abstract="true" eSuperTypes="#//identifier/Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refines" eType="#//RefiningReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedBy" upperBound="-1"
        eType="#//DataFlowDiagram" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//identifier/Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingDataFlow" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingDataFlow" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFlow" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="data" upperBound="-1" eType="#//Data"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="#//dd/DataType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalActor" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//identifier/Identifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="RefiningReference" eSuperTypes="#//identifier/Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="refinedProcesses" lowerBound="1"
        upperBound="-1" eType="#//Process"/>
  </eClassifiers>
  <eSubpackages name="dd" nsURI="http://www.example.org/dd" nsPrefix="dd">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xA;Provides a package for uniquely identifiable elements&#xA;&lt;/p>"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="#//dd/Identifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CompositeDataType" eSuperTypes="#//dd/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entries" lowerBound="1"
          upperBound="-1" eType="#//dd/Entry" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CollectionDataType" eSuperTypes="#//dd/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//dd/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveDataType" eSuperTypes="#//dd/DataType"/>
    <eClassifiers xsi:type="ecore:EClass" name="Entry" eSuperTypes="#//dd/Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1"
          eType="#//dd/DataType"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Identifier" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>&#xA;Inherit from this entity to make an element uniquely identifiable.&lt;br />&#xA;Identifiers&amp;nbsp;are&amp;nbsp;not&amp;nbsp;fixed&amp;nbsp;to&amp;nbsp;one&amp;nbsp;realization.&lt;br />&#xA;GUIDs&amp;nbsp;are&amp;nbsp;recommend.&amp;nbsp;GUIDs&amp;nbsp;are&amp;nbsp;described&amp;nbsp;in&amp;nbsp;their&amp;nbsp;own&amp;nbsp;model.&amp;nbsp;See&amp;nbsp;GUIDModel&amp;nbsp;(GUID.emx).&lt;br />&#xA;Identifier&amp;nbsp;implementations&amp;nbsp;can&amp;nbsp;be&amp;nbsp;found&amp;nbsp;in&amp;nbsp;external&amp;nbsp;projects&amp;nbsp;only.&#xA;&lt;/p>"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="identifierIsUnique" value="Identifier.allInstances()->isUnique(p: Identifier | p.id)"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="identifierIsUnique"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Identifier attribute, in the default PCM implementation, this field is filled with a randomly generated UUID value"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="identifier" nsURI="http://sdq.ipd.uka.de/Identifier/2.1" nsPrefix="identifier">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;p>&#xA;Provides a package for uniquely identifiable elements&#xA;&lt;/p>"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Identifier" abstract="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;p>&#xA;Inherit from this entity to make an element uniquely identifiable.&lt;br />&#xA;Identifiers&amp;nbsp;are&amp;nbsp;not&amp;nbsp;fixed&amp;nbsp;to&amp;nbsp;one&amp;nbsp;realization.&lt;br />&#xA;GUIDs&amp;nbsp;are&amp;nbsp;recommend.&amp;nbsp;GUIDs&amp;nbsp;are&amp;nbsp;described&amp;nbsp;in&amp;nbsp;their&amp;nbsp;own&amp;nbsp;model.&amp;nbsp;See&amp;nbsp;GUIDModel&amp;nbsp;(GUID.emx).&lt;br />&#xA;Identifier&amp;nbsp;implementations&amp;nbsp;can&amp;nbsp;be&amp;nbsp;found&amp;nbsp;in&amp;nbsp;external&amp;nbsp;projects&amp;nbsp;only.&#xA;&lt;/p>"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="identifierIsUnique" value="Identifier.allInstances()->isUnique(p: Identifier | p.id)"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="identifierIsUnique"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Identifier attribute, in the default PCM implementation, this field is filled with a randomly generated UUID value"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
